from .text_load import NODE_CLASS_MAPPINGS as TEXT_LOAD_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TEXT_LOAD_DISPLAY_MAPPINGS
from .custom_image_saver import NODE_CLASS_MAPPINGS as IMAGE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as IMAGE_DISPLAY_MAPPINGS
from .text_saver import NODE_CLASS_MAPPINGS as TEXT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TEXT_DISPLAY_MAPPINGS
from .image_loader import NODE_CLASS_MAPPINGS as LOADER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LOADER_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {**TEXT_LOAD_MAPPINGS, **IMAGE_MAPPINGS, **TEXT_MAPPINGS, **LOADER_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**TEXT_LOAD_DISPLAY_MAPPINGS, **IMAGE_DISPLAY_MAPPINGS, **TEXT_DISPLAY_MAPPINGS, **LOADER_DISPLAY_MAPPINGS}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']