from .dialogue_extractor import NODE_CLASS_MAPPINGS as DIALOGUE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as DIALOGUE_DISPLAY_MAPPINGS
from .custom_image_saver import NODE_CLASS_MAPPINGS as IMAGE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as IMAGE_DISPLAY_MAPPINGS
from .text_saver import NODE_CLASS_MAPPINGS as TEXT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TEXT_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {**DIALOGUE_MAPPINGS, **IMAGE_MAPPINGS, **TEXT_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**DIALOGUE_DISPLAY_MAPPINGS, **IMAGE_DISPLAY_MAPPINGS, **TEXT_DISPLAY_MAPPINGS}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']